# Generated by Django 5.2.1 on 2025-05-24 14:37

import boutique.enums
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Produit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True)),
                ('prix', models.DecimalField(decimal_places=2, max_digits=7)),
                ('stock', models.PositiveIntegerField(default=0)),
                ('vendable', models.BooleanField(default=False)),
                ('categorie', models.CharField(choices=[('CHUTE', 'Chute'), ('PELOTE', 'Pelote'), ('TISSUE', 'Tissu'), ('WATTE', 'Watte'), ('OUTILS', 'Outils'), ('RANGEMENT', 'Rangement'), ('CREATION', 'Création'), ('ACCESSOIRES', 'Accessoires'), ('AUTRE', 'Autre')], default='AUTRE', max_length=20, verbose_name=boutique.enums.ProductCategory)),
            ],
        ),
        migrations.CreateModel(
            name='Cotisant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100)),
                ('prenom', models.CharField(max_length=100)),
                ('solde', models.DecimalField(decimal_places=2, default=0.0, max_digits=7)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Achat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantite', models.PositiveIntegerField()),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('cotisant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='boutique.cotisant')),
                ('produit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='boutique.produit')),
            ],
        ),
    ]
