# Generated by Django 5.2.1 on 2025-05-24 19:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('boutique', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cotisant',
            name='nom',
        ),
        migrations.RemoveField(
            model_name='cotisant',
            name='prenom',
        ),
    ]
